[tasks.check]
command = "cargo"
description = "check the contract syntax is correct the contract"
args = ["+nightly", "check"]
watch = { ignore_pattern = "target"}
dependencies = ["format"]

[tasks.format]
command = "cargo"
description = "format code with default settings"
args = ["fmt"]
